src/index.js

- Fixed when having multiple visualisations on one page
- Babel will load only once

[QPE 575] Load babel only once for a page

---

src/definition/formatted.js
src/initialize-transformed.js

JIRA ticket
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-479

[QPE-479] Qlik defaults

---

src/data-table/data-cell.jsx
src/definition/formatted.js
src/initialize-transformed.js

JIRA ticket
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-554

[QPE-554] text alignemt

---

src/definition/header.js
src/definition/index.js
src/index.js

JIRA ticket
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-477

[QPE-477] Definition object is Qlik standard

---

src/main.less
src/paint.jsx

JIRA ticket
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-484

[QPE-484] Edit mode interactions

---

src/main.less

- same padding for single object mode
https://tretton37.atlassian.net/browse/QPE-600

[QPE 600] Use same layout in single onject mode as in normal mode

---

src/main.less

https://tretton37.atlassian.net/browse/QPE-622

[QPE 622] show scrollbar for easier scrolling

---

src/data-table/header-padding.jsx
src/data-table/row-header.jsx
src/main.less

- Added tooltip for row header
- Better vertical alignment
- Move static styling to css
https://tretton37.atlassian.net/browse/QPE-549

[QPE 549] Minor adjustments for tooltip

---

src/data-table/data-cell.jsx
src/main.less

- Look at the value format to determine if column is percentage based not the name
https://tretton37.atlassian.net/browse/QPE-634

[QPE 634] Fix column width 

---

src/tooltip/index.jsx

https://tretton37.atlassian.net/browse/QPE-631

[QPE 631] Prevent console errors in IE on cell hover

---

src/definition/index.js
src/definition/table-format.js
src/main.less

Contains fixes for these 3:
https://tretton37.atlassian.net/browse/QPE-636
https://tretton37.atlassian.net/browse/QPE-638
https://tretton37.atlassian.net/browse/QPE-639

[QPE 636] Table format fixes

---

src/definition/header.js
src/headers-table/column-header.jsx
src/headers-table/export-column-header.jsx
src/headers-table/measurement-column-header.jsx
src/initialize-transformed.js
src/main.less

https://tretton37.atlassian.net/browse/QPE-637
Font size were not changed when clicking on relevant buttons

[QPE 637] Header format fixes

---

src/headers-table/measurement-column-header.jsx

The header width should match the table format

---

src/data-table/data-cell.jsx
src/data-table/index.jsx
src/initialize-transformed.js

Empty data results in empty cells.
-Previously, empty data resulted in the cells
completely missing. This caused other cells
to not end up in the correct column.
Issue: DEB-154
Arrange matching dim1 data on the same row.
-The data is not guaranteed to be processed row
by row. Therefore, make sure to check the entire
matrix for the correct row (not just previous row)
when appending new row data.
Issue: DEB-155

Improved setup of data matrix

---

src/index.js

-Dynamic max values for Dimensions and Measures.
Issue: DEB-157

1 Dim and 9 Measures OR 2 Dim and 8 Measures

---

src/definition/index.js

Changed order of properties and added About

---

src/dataset.js
src/definition/table-format.js
src/initialize-transformed.js
src/paint.jsx
src/store.js

-According to the documentation it should only be
possible to set two dimensions. Previously you
were able to set three, where the third one was
used for styling. This wasn't obvious to the user
though. Now, the design field is set under
Appearance -> Table format.
Issue: DEB-156

Moved design dimension to Appearance->Table format

---

src/definition/pagination.js

-Previous isn't grammatically correct.
Issue: DEB-160

Updated default error message

---

src/data-table/data-cell.jsx
src/data-table/index.jsx
src/data-table/row-header.jsx
src/headers-table/column-header.jsx
src/headers-table/export-column-header.jsx
src/headers-table/index.jsx
src/headers-table/measurement-column-header.jsx
src/initialize-transformed.js
src/main.less
src/root.jsx
src/tooltip/index.jsx

-Only add elements that are displayed.
-Properly align content.
-Use correct font.
Issue: DEB-163, DEB-164

Improved header arrangement

---

gulpfile.js

Updated the icon to pivot-table

---

src/initialize-transformed.js

If dimension value doesn't contain qText use qNum

---

src/initialize-transformed.js

-Recent commit introduced a bug that prevented
single-dimension tables from showing any cells.
Issue: DEB-176

Show cells for single-dimension tables

---

src/main.less

Fixed cellspacing on IE, Edge and FF

---

src/headers-table/column-header.jsx
src/headers-table/index.jsx
src/headers-table/measurement-column-header.jsx
src/main.less
src/root.jsx
stylelint.config.js

-Now using flexbox to make the layout more
dynamic.
Issue: DEB-188, DEB-192

Fixed layout and styling of table

---

src/data-table/data-cell.jsx
src/definition/conditional-coloring.js
src/initialize-transformed.js

-Used to specify what measure columns should
use conditional coloring.
Issue: DEB-187

Color by measure indices

---

src/definition/conditional-coloring.js
src/definition/header.js
src/definition/pagination.js
src/definition/table-format.js

Updated string according to Ralf Narfeldt

---

src/dataset.js

-Previously the smart pivot didn't render as
a master object.
Issue: DEB-173

Fixed master object bug

---

src/data-table/data-cell.jsx
src/masking.js
src/utilities.js

Reverts qlik-oss/PLSmartPivot#59

Revert "Fixed cell number formatting"

---

src/data-table/data-cell.jsx
src/definition/table-format.js
src/headers-table/column-header.jsx
src/headers-table/index.jsx
src/headers-table/measurement-column-header.jsx
src/initialize-transformed.js
src/main.less

-Previous slider only has three presets, this new
solution sets the actual width.
Issue: DEB-221

Slider for cell width without presets

---

src/excel-export.js

-It is not possible to specify "from:".
Issue: QLIK-95963

Specifying excel type of excel download

---

src/excel-export.js
src/export-button.jsx
src/headers-table/export-column-header.jsx
src/headers-table/index.jsx

-No tid-element available when inside native container.
Therefore, use root element to find table cells instead.
Issue: DEB-242

Excel export inside container

---

src/data-table/index.jsx
src/headers-table/index.jsx

-This makes it possible to use the same measurement
multiple times within the same smart-pivot chart.
Issue: DEB-232

Made the table cell keys more unique

---

src/data-table/data-cell.jsx
src/data-table/index.jsx
src/definition/table-format.js
src/headers-table/column-header.jsx
src/headers-table/index.jsx
src/headers-table/measurement-column-header.jsx
src/initialize-transformed.js
src/main.less
src/root.jsx
src/utilities.js

-To achieve pixel perfection the container of both
header and data needs to calculate the size of the
child tables' cells.
Issue: QLIK-95962

Add option to fit cells to chart width

---

src/data-table/data-cell.jsx
src/data-table/index.jsx
src/data-table/row-header.jsx
src/dataset.js
src/headers-table/column-header.jsx
src/headers-table/index.jsx
src/initialize-transformed.js

-Makes it possible to select master fields with
different names than the original field.
-Alternate state is no longer a problem when using
this technique to select.
Issue: DEB-250

Selecting with backendApi instead of Field

---

src/dataset.js
src/index.js

Suppress missing values and use correct cube size

---

webpack.config.js

Doing this change for one extension. Once approved, shall replicate it to all that have 'source-map'.

Removing source maps from production mode.

---

.eslintrc.js
src/initialize-transformed.js
src/root.jsx

The Pivot enters an infinite re-render loop when in fullscreen due to a REF and a forcedUpdate.
Contains a bunch of lint changes, but can't really be to bothered with avoiding them.
@veinfors Add someone extra from your team if you want.

fix: remove infinite loop
